
services:
  app:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development